export const FETCH_COUNTRIES = 'FETCH_COUNTRIES';
export const FETCH_CAPITAL = 'FETCH_CAPITAL';
export const FETCH_CURRENCY = 'FETCH_CURRENCY';
export const FETCH_REGION_BLOCKS = 'FETCH_REGION_BLOCKS';
export const BASE_URL = 'BASE_URL';
